### ISSUE TITLE
License

### ISSUE THREAD

**Issue by code-affinity** [LaurentBerger/ColorMatchTemplate#1]
Could you choose/publish a license for this repository so I know how I may use it?

**Comment by LaurentBerger** [comment]
you can use this code inside [opencv](https://docs.opencv.org/trunk/da/d17/group__ximgproc__filters.html#ga370f180e4a52231ba218adbb4a65a9ca)

[Sample ](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/samples/color_match_template.cpp)

You must check license in [papers](https://github.com/opencv/opencv_contrib/pull/1791#issue-217525060). I think there is no problem
